<a href="https://colab.research.google.com/github/sandeepss2020/Neural_Network-DL/blob/main/LAB5_NNDL_PRACTICE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [52]:
import numpy as np
import matplotlib.pyplot as plt
from numpy import array , empty, zeros , ones
import random

1. Explore the commands relevant to the following identities/outputs with different input values.

  a. Identity
b. ones
c. zeros
d. sum
e. size
f. Linear spaced data
g. random

In [5]:
 f = np.eye(5)
 print(f)             #create a 5 x5 identity matrix

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [15]:
 F = np.eye(3, k=1)
 print(F)             #Creating a 3 x 3 Sparse matrix(most of the elements are zero)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [16]:
 G = np.mat(np.identity(2)) 
 print(G)

[[1. 0.]
 [0. 1.]]


In [27]:
A = array([[1,2,3],[1,2,3],[1,2,3]])
print(A)

A.sum()     #Array-wise sum


[[1 2 3]
 [1 2 3]
 [1 2 3]]


18

In [21]:
B = empty([3,3])
print(B)

[[4.9e-324 9.9e-324 1.5e-323]
 [4.9e-324 9.9e-324 1.5e-323]
 [4.9e-324 9.9e-324 1.5e-323]]


In [29]:

C = zeros([3,5])
print(C)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [26]:
D = ones([5, 5])
print(D)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [32]:
print(A.sum()) 
D.cumsum(axis=1)    #Cummulative sum of elements

18


array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])

In [ ]:
print(D.shape)     #gives rows and coloumns
print(D.size)

In [37]:
np.resize(D,(2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [40]:
D.resize((2,3), refcheck=False)
print(D)

[[1. 1. 1.]
 [1. 1. 1.]]


In [38]:
D.shape

(5, 5)

In [46]:
print(D)
print(D.size)
print(D.shape)

[[1. 1. 1.]
 [1. 1. 1.]]
6
(2, 3)


In [62]:
np.random.random((3,2))


array([[0.54702252, 0.25732457],
       [0.95221186, 0.05210256],
       [0.86953473, 0.68104803]])

In [50]:
E = np.matrix(np.random.random((2,2)))
print(E)

[[0.36976184 0.77165539]
 [0.33547995 0.38668821]]


In [63]:
print(random.randrange(3, 9))

8
