<a href="https://colab.research.google.com/github/sandeepss2020/Neural_Network-DL/blob/main/NNDL_LAB8(1)_CNN_CALCULATION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from math import exp
from random import seed
from random import random
import numpy as np

seed(1)

In [2]:
class POOL_TYPE:
  MAX = "max"
  AVG = "avg"
  SUM = "sum"

  def __str__(self):
    return "Pooling types available: POOL_TYPE.MAX, POOL_TYPE.AVG, and POOL_TYPE.SUM"

class InvalidPoolingTypeException(Exception):
  pass

In [3]:
data = np.array([
    [1, 0, 1, 1, 0],
    [0, 0, 0, 1, 1],
    [1, 0, 0, 0, 1],
    [0, 1, 1, 1, 0],
    [1, 1, 0, 1, 0]
])

kernel = np.array([
    [1, 0, 0],
    [0, 0, 1],
    [1, 1, 0]
])

In [6]:
def do_stride(data: np.array, kernel: np.array, stride: int) -> np.array:
  output = []
  row, col = 0, 0

  while row + len(kernel) <= len(data):
    output_row = []
    output.append(output_row)
    col = 0

    while col + len(kernel) <= len(data[0]):
      output_row.append(np.sum(data[row:row + len(kernel), col:col + len(kernel)] * kernel))
      col += stride
    
    row += stride
  
  return np.array(output)

In [7]:
def pooling(data: np.array, pool_type: POOL_TYPE = POOL_TYPE.MAX, pooling_size: int = 2) -> np.array:
  output = []
  row, col = 0, 0

  while row + pooling_size <= len(data):
    output_row = []
    output.append(output_row)
    col = 0

    while col + pooling_size <= len(data[0]):
      if pool_type == POOL_TYPE.MAX:
        output_row.append(np.amax(data[row:row + pooling_size, col:col + pooling_size]))
      elif pool_type == POOL_TYPE.AVG:
        output_row.append(np.average(data[row:row + pooling_size, col:col + pooling_size]))
      elif pool_type == POOL_TYPE.SUM:
        output_row.append(np.sum(data[row:row + pooling_size, col:col + pooling_size]))
      else:
        raise InvalidPoolingTypeException(f"No pooling type { pool_type }. { POOL_TYPE() }")
      col += 1
    
    row += 1
  
  return np.array(output)

In [8]:
stride1 = do_stride(data, kernel, 1)
stride2 = do_stride(data, kernel, 2)

print("Stride 1:\n", stride1)
print("\nStride 2:\n", stride2)

Stride 1:
 [[2 1 2]
 [1 2 3]
 [4 2 1]]

Stride 2:
 [[2 2]
 [4 1]]


In [9]:
max_pool_1 = pooling(stride1)
avg_pool_1 = pooling(stride1, POOL_TYPE.AVG)
sum_pool_1 = pooling(stride1, POOL_TYPE.SUM)

print("Max pooling on stride 1:\n", max_pool_1)
print("Average pooling on stride 1:\n", avg_pool_1)
print("Sum pooling on stride 1:\n", sum_pool_1)

max_pool_2 = pooling(stride2)
avg_pool_2 = pooling(stride2, POOL_TYPE.AVG)
sum_pool_2 = pooling(stride2, POOL_TYPE.SUM)

print("\nMax pooling on stride 1:\n", max_pool_2)
print("Average pooling on stride 1:\n", avg_pool_2)
print("Sum pooling on stride 1:\n", sum_pool_2)

Max pooling on stride 1:
 [[2 3]
 [4 3]]
Average pooling on stride 1:
 [[1.5  2.  ]
 [2.25 2.  ]]
Sum pooling on stride 1:
 [[6 8]
 [9 8]]

Max pooling on stride 1:
 [[4]]
Average pooling on stride 1:
 [[2.25]]
Sum pooling on stride 1:
 [[9]]


In [10]:
for label, data in zip(
    ["Max Pooling Stride 1", "Avg Pooling Stride 1", "Sum Pooling Stride 1", "Max Pooling Stride 2", "Avg Pooling Stride 2", "Sum Pooling Stride 2"],
    [max_pool_1, avg_pool_1, sum_pool_1, max_pool_2, avg_pool_2, sum_pool_2]
):
  print(label, "\n", data.flatten())

Max Pooling Stride 1 
 [2 3 4 3]
Avg Pooling Stride 1 
 [1.5  2.   2.25 2.  ]
Sum Pooling Stride 1 
 [6 8 9 8]
Max Pooling Stride 2 
 [4]
Avg Pooling Stride 2 
 [2.25]
Sum Pooling Stride 2 
 [9]
